with open('app/schemas/__init__.py', 'a') as f:
    f.write('\n\nclass FinancialInsight(BaseModel):\n')
    f.write('    client_id: int = 0\n')
    f.write('    period: str = ""\n')
    f.write('    total_income: float = 0\n')
    f.write('    total_expenses: float = 0\n')
    f.write('    net_profit: float = 0\n')
    f.write('    profit_margin: float = 0\n')
    f.write('    top_expense_categories: List[Dict] = []\n')
    f.write('    gst_liability: float = 0\n')
    f.write('    tds_liability: float = 0\n')
    f.write('    health_score: float = 0\n')
    f.write('    health_indicators: List[str] = []\n')
    f.write('\n\nclass GSTSummary(BaseModel):\n')
    f.write('    period: str = ""\n')
    f.write('    total_sales: float = 0\n')
    f.write('    total_purchases: float = 0\n')
    f.write('    output_gst: float = 0\n')
    f.write('    input_gst: float = 0\n')
    f.write('    net_gst_payable: float = 0\n')
    f.write('    mismatches_count: int = 0\n')
print('Done')