# -*- coding: utf-8 -*-
import os

BACK = r'C:\ai-ca-copilot\ai-ca-copilot\backend'
FRONT_PAGES = r'C:\ai-ca-copilot\ai-ca-copilot\frontend\src\pages'
FRONT_SRC = r'C:\ai-ca-copilot\ai-ca-copilot\frontend\src'

# ── 1. PDF Export Service ─────────────────────────────────────────────────
pdf_service = '''# -*- coding: utf-8 -*-
import io
from datetime import datetime

def generate_invoice_pdf(invoice_data, client_data):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm, leftMargin=2*cm, rightMargin=2*cm)
        styles = getSampleStyleSheet()
        elements = []
        elements.append(Paragraph("TAX INVOICE", styles['Title']))
        elements.append(Spacer(1, 0.5*cm))
        elements.append(Paragraph(f"Invoice #: {invoice_data.get('invoice_number','N/A')}", styles['Normal']))
        elements.append(Paragraph(f"Date: {invoice_data.get('invoice_date','')}", styles['Normal']))
        elements.append(Paragraph(f"Client: {client_data.get('company_name','')}", styles['Normal']))
        elements.append(Paragraph(f"GSTIN: {client_data.get('gstin','')}", styles['Normal']))
        elements.append(Spacer(1, 0.5*cm))
        data = [
            ['Description', 'Taxable Amount', 'CGST', 'SGST', 'IGST', 'Total'],
            ['Services/Goods', f"Rs.{invoice_data.get('taxable_amount',0):,.2f}",
             f"Rs.{invoice_data.get('cgst_amount',0):,.2f}",
             f"Rs.{invoice_data.get('sgst_amount',0):,.2f}",
             f"Rs.{invoice_data.get('igst_amount',0):,.2f}",
             f"Rs.{invoice_data.get('total_amount',0):,.2f}"],
        ]
        t = Table(data, colWidths=[5*cm, 3*cm, 2.5*cm, 2.5*cm, 2.5*cm, 3*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a1a2e')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTSIZE', (0,0), (-1,-1), 9),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('ALIGN', (1,0), (-1,-1), 'RIGHT'),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.5*cm))
        elements.append(Paragraph(f"<b>Total Amount: Rs.{invoice_data.get('total_amount',0):,.2f}</b>", styles['Normal']))
        elements.append(Paragraph("Generated by Maavi AI Copilot Pro", styles['Normal']))
        doc.build(elements)
        buf.seek(0)
        return buf
    except ImportError:
        buf = io.BytesIO()
        content = f"""TAX INVOICE
Invoice #: {invoice_data.get('invoice_number','N/A')}
Date: {invoice_data.get('invoice_date','')}
Client: {client_data.get('company_name','')}
GSTIN: {client_data.get('gstin','')}
Total Amount: Rs.{invoice_data.get('total_amount',0):,.2f}
Generated by Maavi AI Copilot Pro"""
        buf.write(content.encode())
        buf.seek(0)
        return buf

def generate_report_pdf(report_data, client_name, period):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm, leftMargin=2*cm, rightMargin=2*cm)
        styles = getSampleStyleSheet()
        elements = []
        elements.append(Paragraph(f"Financial Report - {client_name}", styles['Title']))
        elements.append(Paragraph(f"Period: {period}", styles['Normal']))
        elements.append(Paragraph(f"Generated: {datetime.now().strftime('%d %b %Y')}", styles['Normal']))
        elements.append(Spacer(1, 0.5*cm))
        summary_data = [
            ['Metric', 'Amount'],
            ['Total Revenue', f"Rs.{report_data.get('total_revenue',0):,.2f}"],
            ['Total Expenses', f"Rs.{report_data.get('total_expenses',0):,.2f}"],
            ['Net Profit', f"Rs.{report_data.get('net_profit',0):,.2f}"],
            ['Output GST', f"Rs.{report_data.get('output_gst',0):,.2f}"],
            ['Input GST', f"Rs.{report_data.get('input_gst',0):,.2f}"],
            ['Net GST Payable', f"Rs.{report_data.get('net_gst',0):,.2f}"],
        ]
        t = Table(summary_data, colWidths=[8*cm, 6*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a1a2e')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTSIZE', (0,0), (-1,-1), 10),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('ALIGN', (1,0), (-1,-1), 'RIGHT'),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f5f5f5')]),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.5*cm))
        elements.append(Paragraph("Generated by Maavi AI Copilot Pro", styles['Normal']))
        doc.build(elements)
        buf.seek(0)
        return buf
    except ImportError:
        buf = io.BytesIO()
        content = f"Financial Report - {client_name}\\nPeriod: {period}\\nGenerated by Maavi AI Copilot Pro"
        buf.write(content.encode())
        buf.seek(0)
        return buf
'''
os.makedirs(os.path.join(BACK, 'app', 'services', 'pdf'), exist_ok=True)
open(os.path.join(BACK, 'app', 'services', 'pdf', '__init__.py'), 'w').write('')
open(os.path.join(BACK, 'app', 'services', 'pdf', 'pdf_service.py'), 'w', encoding='utf-8').write(pdf_service)
print('1. PDF service created')

# Install reportlab
os.system('pip install reportlab --break-system-packages -q')
print('2. reportlab installed')

# ── 2. GSTR-2B Reconciliation Service ────────────────────────────────────
gstr2b_service = '''# -*- coding: utf-8 -*-
import json
from sqlalchemy.orm import Session
from app.models import Invoice

def reconcile_gstr2b(client_id: int, gstr2b_data: dict, db: Session):
    """Match GSTR-2B data against purchase invoices in DB"""
    invoices = db.query(Invoice).filter(
        Invoice.client_id == client_id,
        Invoice.invoice_type == "purchase"
    ).all()
    
    gstr2b_invoices = gstr2b_data.get("data", {}).get("docdata", {}).get("b2b", [])
    
    matched = []
    unmatched_portal = []
    unmatched_books = []
    
    portal_gstin_map = {}
    for supplier in gstr2b_invoices:
        gstin = supplier.get("ctin", "")
        for inv in supplier.get("inv", []):
            key = f"{gstin}_{inv.get('inum','')}"
            portal_gstin_map[key] = {
                "gstin": gstin,
                "invoice_number": inv.get("inum",""),
                "invoice_date": inv.get("idt",""),
                "taxable_value": inv.get("val",0),
                "igst": inv.get("itms",[{}])[0].get("itm_det",{}).get("iamt",0),
                "cgst": inv.get("itms",[{}])[0].get("itm_det",{}).get("camt",0),
                "sgst": inv.get("itms",[{}])[0].get("itm_det",{}).get("samt",0),
            }
    
    books_map = {}
    for inv in invoices:
        if inv.vendor_gstin and inv.invoice_number:
            key = f"{inv.vendor_gstin}_{inv.invoice_number}"
            books_map[key] = inv
    
    all_keys = set(list(portal_gstin_map.keys()) + list(books_map.keys()))
    
    for key in all_keys:
        if key in portal_gstin_map and key in books_map:
            portal = portal_gstin_map[key]
            book = books_map[key]
            diff = abs((portal.get("taxable_value",0) or 0) - (book.taxable_amount or 0))
            matched.append({
                "invoice_number": book.invoice_number,
                "vendor_gstin": book.vendor_gstin,
                "books_amount": book.taxable_amount,
                "portal_amount": portal.get("taxable_value",0),
                "difference": diff,
                "status": "matched" if diff < 1 else "amount_mismatch"
            })
        elif key in portal_gstin_map:
            p = portal_gstin_map[key]
            unmatched_portal.append({
                "invoice_number": p.get("invoice_number"),
                "vendor_gstin": p.get("gstin"),
                "portal_amount": p.get("taxable_value",0),
                "status": "missing_in_books"
            })
        else:
            b = books_map[key]
            unmatched_books.append({
                "invoice_number": b.invoice_number,
                "vendor_gstin": b.vendor_gstin,
                "books_amount": b.taxable_amount,
                "status": "missing_in_portal"
            })
    
    total_itc_available = sum(
        (p.get("igst",0) or 0) + (p.get("cgst",0) or 0) + (p.get("sgst",0) or 0)
        for p in portal_gstin_map.values()
    )
    
    return {
        "total_portal_invoices": len(portal_gstin_map),
        "total_books_invoices": len(books_map),
        "matched": len([m for m in matched if m["status"] == "matched"]),
        "amount_mismatch": len([m for m in matched if m["status"] == "amount_mismatch"]),
        "missing_in_books": len(unmatched_portal),
        "missing_in_portal": len(unmatched_books),
        "total_itc_available": round(total_itc_available, 2),
        "matched_records": matched,
        "unmatched_portal": unmatched_portal,
        "unmatched_books": unmatched_books,
    }
'''
os.makedirs(os.path.join(BACK, 'app', 'services', 'gstr2b'), exist_ok=True)
open(os.path.join(BACK, 'app', 'services', 'gstr2b', '__init__.py'), 'w').write('')
open(os.path.join(BACK, 'app', 'services', 'gstr2b', 'reconcile.py'), 'w', encoding='utf-8').write(gstr2b_service)
print('3. GSTR-2B reconciliation service created')

# ── 3. Extra Routes (PDF, GSTR2B, Trial Balance, Legal Invoice) ───────────
extra_routes = '''# -*- coding: utf-8 -*-
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from sqlalchemy import func
from pydantic import BaseModel
from typing import Optional
from datetime import date
from app.db.database import get_db
from app.models import Client, Invoice, Transaction, ComplianceItem, User
from app.core.security import get_current_user

extra_router = APIRouter(prefix="/extra", tags=["Extra Features"])

# ── PDF Export ────────────────────────────────────────────────────────────
@extra_router.get("/invoice/{invoice_id}/pdf")
def export_invoice_pdf(invoice_id: int, db: Session = Depends(get_db), u: User = Depends(get_current_user)):
    inv = db.query(Invoice).filter(Invoice.id == invoice_id).first()
    if not inv:
        raise HTTPException(status_code=404, detail="Invoice not found")
    client = db.query(Client).filter(Client.id == inv.client_id).first()
    from app.services.pdf.pdf_service import generate_invoice_pdf
    invoice_data = {
        "invoice_number": inv.invoice_number,
        "invoice_date": str(inv.invoice_date) if inv.invoice_date else "",
        "taxable_amount": inv.taxable_amount or 0,
        "cgst_amount": inv.cgst_amount or 0,
        "sgst_amount": inv.sgst_amount or 0,
        "igst_amount": inv.igst_amount or 0,
        "total_amount": inv.total_amount or 0,
    }
    client_data = {
        "company_name": client.company_name if client else "",
        "gstin": client.gstin if client else "",
    }
    pdf_buf = generate_invoice_pdf(invoice_data, client_data)
    return StreamingResponse(pdf_buf, media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=invoice_{inv.invoice_number}.pdf"})

@extra_router.get("/client/{client_id}/report-pdf")
def export_report_pdf(client_id: int, period: str = "FY 2024-25", db: Session = Depends(get_db), u: User = Depends(get_current_user)):
    client = db.query(Client).filter(Client.id == client_id, Client.ca_user_id == u.id).first()
    if not client:
        raise HTTPException(status_code=404, detail="Client not found")
    invoices = db.query(Invoice).filter(Invoice.client_id == client_id).all()
    sales = [i for i in invoices if i.invoice_type and i.invoice_type.value == "sale"]
    purchases = [i for i in invoices if i.invoice_type and i.invoice_type.value == "purchase"]
    report_data = {
        "total_revenue": sum(i.total_amount or 0 for i in sales),
        "total_expenses": sum(i.total_amount or 0 for i in purchases),
        "net_profit": sum(i.total_amount or 0 for i in sales) - sum(i.total_amount or 0 for i in purchases),
        "output_gst": sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in sales),
        "input_gst": sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in purchases),
        "net_gst": sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in sales) - sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in purchases),
    }
    from app.services.pdf.pdf_service import generate_report_pdf
    pdf_buf = generate_report_pdf(report_data, client.company_name, period)
    return StreamingResponse(pdf_buf, media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=report_{client.company_name}_{period}.pdf"})

# ── Trial Balance ─────────────────────────────────────────────────────────
@extra_router.get("/client/{client_id}/trial-balance")
def trial_balance(client_id: int, db: Session = Depends(get_db), u: User = Depends(get_current_user)):
    client = db.query(Client).filter(Client.id == client_id, Client.ca_user_id == u.id).first()
    if not client:
        raise HTTPException(status_code=404, detail="Client not found")
    invoices = db.query(Invoice).filter(Invoice.client_id == client_id).all()
    sales = [i for i in invoices if i.invoice_type and i.invoice_type.value == "sale"]
    purchases = [i for i in invoices if i.invoice_type and i.invoice_type.value == "purchase"]
    total_sales = sum(i.taxable_amount or 0 for i in sales)
    total_purchases = sum(i.taxable_amount or 0 for i in purchases)
    output_gst = sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in sales)
    input_gst = sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in purchases)
    gross_profit = total_sales - total_purchases
    accounts = [
        {"account": "Sales Revenue", "type": "Income", "debit": 0, "credit": round(total_sales, 2)},
        {"account": "Cost of Purchases", "type": "Expense", "debit": round(total_purchases, 2), "credit": 0},
        {"account": "Gross Profit", "type": "Income", "debit": 0, "credit": round(gross_profit, 2)},
        {"account": "Output GST Payable", "type": "Liability", "debit": 0, "credit": round(output_gst, 2)},
        {"account": "Input GST Credit", "type": "Asset", "debit": round(input_gst, 2), "credit": 0},
        {"account": "Net GST Payable", "type": "Liability", "debit": 0, "credit": round(output_gst - input_gst, 2)},
    ]
    total_debit = sum(a["debit"] for a in accounts)
    total_credit = sum(a["credit"] for a in accounts)
    return {
        "client": client.company_name,
        "accounts": accounts,
        "total_debit": round(total_debit, 2),
        "total_credit": round(total_credit, 2),
        "balanced": abs(total_debit - total_credit) < 1,
        "gross_profit": round(gross_profit, 2),
        "net_profit": round(gross_profit, 2),
    }

# ── P&L Statement ─────────────────────────────────────────────────────────
@extra_router.get("/client/{client_id}/pnl")
def pnl_statement(client_id: int, db: Session = Depends(get_db), u: User = Depends(get_current_user)):
    client = db.query(Client).filter(Client.id == client_id, Client.ca_user_id == u.id).first()
    if not client:
        raise HTTPException(status_code=404, detail="Client not found")
    invoices = db.query(Invoice).filter(Invoice.client_id == client_id).all()
    sales = [i for i in invoices if i.invoice_type and i.invoice_type.value == "sale"]
    purchases = [i for i in invoices if i.invoice_type and i.invoice_type.value == "purchase"]
    revenue = sum(i.taxable_amount or 0 for i in sales)
    expenses = sum(i.taxable_amount or 0 for i in purchases)
    gross_profit = revenue - expenses
    tax_estimate = gross_profit * 0.25 if gross_profit > 0 else 0
    net_profit = gross_profit - tax_estimate
    return {
        "client": client.company_name,
        "income": [
            {"head": "Revenue from Operations", "amount": round(revenue, 2)},
            {"head": "Other Income", "amount": 0},
        ],
        "total_income": round(revenue, 2),
        "expenses": [
            {"head": "Cost of Materials/Services", "amount": round(expenses, 2)},
            {"head": "Employee Benefits", "amount": 0},
            {"head": "Finance Costs", "amount": 0},
            {"head": "Other Expenses", "amount": 0},
        ],
        "total_expenses": round(expenses, 2),
        "gross_profit": round(gross_profit, 2),
        "tax_estimate": round(tax_estimate, 2),
        "net_profit": round(net_profit, 2),
        "profit_margin": round((net_profit / revenue * 100) if revenue > 0 else 0, 1),
    }

# ── GSTR-2B Reconciliation ────────────────────────────────────────────────
@extra_router.post("/client/{client_id}/gstr2b-reconcile")
async def gstr2b_reconcile(client_id: int, file: UploadFile = File(...), db: Session = Depends(get_db), u: User = Depends(get_current_user)):
    import json
    client = db.query(Client).filter(Client.id == client_id, Client.ca_user_id == u.id).first()
    if not client:
        raise HTTPException(status_code=404, detail="Client not found")
    try:
        content = await file.read()
        gstr2b_data = json.loads(content)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON file. Upload GSTR-2B JSON from GST portal.")
    from app.services.gstr2b.reconcile import reconcile_gstr2b
    result = reconcile_gstr2b(client_id, gstr2b_data, db)
    return result

# ── Legal Invoice Generator ───────────────────────────────────────────────
@extra_router.post("/law/generate-invoice")
def generate_legal_invoice(data: dict, db: Session = Depends(get_db), u: User = Depends(get_current_user)):
    from app.models.law import TimeEntry, Matter
    matter_id = data.get("matter_id")
    matter = db.query(Matter).filter(Matter.id == matter_id, Matter.ca_user_id == u.id).first()
    if not matter:
        raise HTTPException(status_code=404, detail="Matter not found")
    entries = db.query(TimeEntry).filter(TimeEntry.matter_id == matter_id, TimeEntry.is_billed == False).all()
    if not entries:
        raise HTTPException(status_code=400, detail="No unbilled time entries found")
    total_hours = sum(e.hours for e in entries)
    total_amount = sum(e.amount or (e.hours * e.rate_per_hour) for e in entries)
    gst_amount = total_amount * 0.18
    invoice_data = {
        "matter_number": matter.matter_number,
        "client_name": matter.client_name,
        "total_hours": round(total_hours, 1),
        "total_amount": round(total_amount, 2),
        "gst_18pct": round(gst_amount, 2),
        "grand_total": round(total_amount + gst_amount, 2),
        "entries": [{"date": str(e.entry_date), "hours": e.hours, "description": e.description, "amount": e.amount} for e in entries],
    }
    for e in entries:
        e.is_billed = True
    db.commit()
    return invoice_data

# ── Limitation Period Calculator ──────────────────────────────────────────
@extra_router.post("/law/limitation-period")
def calc_limitation(data: dict, u: User = Depends(get_current_user)):
    from datetime import datetime, timedelta
    cause_date_str = data.get("cause_of_action_date")
    case_type = data.get("case_type", "civil")
    if not cause_date_str:
        raise HTTPException(status_code=400, detail="cause_of_action_date required")
    try:
        cause_date = datetime.strptime(cause_date_str, "%Y-%m-%d").date()
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid date format. Use YYYY-MM-DD")
    limits = {
        "civil": {"years": 3, "act": "Limitation Act 1963 - Article 113"},
        "cheque_bounce": {"years": 0, "days": 30, "act": "NI Act Section 138"},
        "consumer": {"years": 2, "act": "Consumer Protection Act 2019"},
        "labour": {"years": 3, "act": "Industrial Disputes Act"},
        "property": {"years": 12, "act": "Limitation Act 1963 - Article 65"},
        "contract": {"years": 3, "act": "Limitation Act 1963 - Article 55"},
        "tort": {"years": 3, "act": "Limitation Act 1963"},
        "execution": {"years": 12, "act": "Limitation Act 1963 - Article 136"},
    }
    limit = limits.get(case_type, limits["civil"])
    years = limit.get("years", 3)
    extra_days = limit.get("days", 0)
    from dateutil.relativedelta import relativedelta
    try:
        expiry = cause_date + relativedelta(years=years) + timedelta(days=extra_days)
    except Exception:
        expiry = cause_date.replace(year=cause_date.year + years)
    today = date.today()
    days_remaining = (expiry - today).days
    return {
        "cause_of_action_date": str(cause_date),
        "case_type": case_type,
        "limitation_period": f"{years} years" if years else f"{extra_days} days",
        "expiry_date": str(expiry),
        "days_remaining": days_remaining,
        "is_expired": days_remaining < 0,
        "is_urgent": 0 <= days_remaining <= 90,
        "applicable_law": limit.get("act",""),
        "status": "EXPIRED" if days_remaining < 0 else "URGENT" if days_remaining <= 90 else "VALID",
    }

# ── WhatsApp Alert (Twilio) ───────────────────────────────────────────────
@extra_router.post("/alerts/whatsapp-test")
def test_whatsapp(data: dict, u: User = Depends(get_current_user)):
    phone = data.get("phone")
    message = data.get("message", "Test message from Maavi AI Copilot Pro")
    try:
        from app.core.config import settings
        account_sid = getattr(settings, "TWILIO_ACCOUNT_SID", "")
        auth_token = getattr(settings, "TWILIO_AUTH_TOKEN", "")
        from_number = getattr(settings, "TWILIO_WHATSAPP_NUMBER", "")
        if not account_sid or not auth_token:
            return {"sent": False, "message": "Twilio not configured. Add TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN to .env"}
        from twilio.rest import Client
        client = Client(account_sid, auth_token)
        msg = client.messages.create(body=message, from_=f"whatsapp:{from_number}", to=f"whatsapp:{phone}")
        return {"sent": True, "sid": msg.sid}
    except ImportError:
        return {"sent": False, "message": "Install twilio: pip install twilio"}
    except Exception as e:
        return {"sent": False, "message": str(e)}

# ── Password Reset ────────────────────────────────────────────────────────
import secrets
from pydantic import BaseModel

class ResetRequest(BaseModel):
    email: str

class ResetConfirm(BaseModel):
    token: str
    new_password: str

reset_tokens = {}

@extra_router.post("/auth/forgot-password")
def forgot_password(data: ResetRequest, db: Session = Depends(get_db)):
    user = db.query(User).filter(User.email == data.email).first()
    if not user:
        return {"message": "If this email exists, a reset link has been sent"}
    token = secrets.token_urlsafe(32)
    reset_tokens[token] = user.id
    from app.services.email.email_service import send_email
    body = f"<h2>Password Reset - Maavi</h2><p>Your reset token: <code>{token}</code></p><p>Use this token to reset your password. Valid for 1 hour.</p>"
    send_email(user.email, "Maavi - Password Reset Request", body)
    return {"message": "Reset link sent if email exists", "dev_token": token}

@extra_router.post("/auth/reset-password")
def reset_password(data: ResetConfirm, db: Session = Depends(get_db)):
    user_id = reset_tokens.get(data.token)
    if not user_id:
        raise HTTPException(status_code=400, detail="Invalid or expired reset token")
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    from app.core.security import get_password_hash
    user.hashed_password = get_password_hash(data.new_password)
    db.commit()
    del reset_tokens[data.token]
    return {"message": "Password reset successfully"}
'''

open(os.path.join(BACK, 'app', 'api', 'routes', 'extra_routes.py'), 'w', encoding='utf-8').write(extra_routes)
print('4. Extra routes created (PDF, GSTR2B, Trial Balance, P&L, Legal Invoice, Limitation, WhatsApp, Password Reset)')

# ── 4. Update main.py ─────────────────────────────────────────────────────
main_path = os.path.join(BACK, 'main.py')
content = open(main_path, encoding='utf-8').read()
if 'extra_router' not in content:
    content = content.replace(
        '    from app.api.routes.law_routes import law_router',
        '    from app.api.routes.law_routes import law_router\n    from app.api.routes.extra_routes import extra_router'
    )
    last = '    app.include_router(law_router, prefix="/api/v1")'
    content = content.replace(last, last + '\n    app.include_router(extra_router, prefix="/api/v1")')
    open(main_path, 'w', encoding='utf-8').write(content)
    print('5. main.py updated with extra_router')
else:
    print('5. extra_router already in main.py')

# ── 5. Legal Research AI Update ───────────────────────────────────────────
legal_ai_path = os.path.join(BACK, 'app', 'services', 'ai', 'legal_ai.py')
content = open(legal_ai_path, encoding='utf-8').read()
if 'precedent_search' not in content:
    addition = '''
def precedent_search(matter_type, facts, court=""):
    system_msg = """You are a senior Indian advocate. Find relevant precedents and case law.
For each case provide: case name, citation, court, year, ratio decidendi, and relevance to current matter.
Format clearly with numbering."""
    user_msg = f"Matter type: {matter_type}\\nFacts: {facts}\\nCourt: {court}\\n\\nFind 3-5 most relevant Indian court precedents."
    return _call_ai(system_msg, user_msg)

def analyze_evidence(evidence_list, matter_type):
    system_msg = "You are an Indian advocate. Analyze the evidence list for strength, admissibility under Indian Evidence Act, and strategic value."
    user_msg = f"Matter type: {matter_type}\\nEvidence list:\\n" + "\\n".join(f"- {e}" for e in evidence_list)
    return _call_ai(system_msg, user_msg)
'''
    open(legal_ai_path, 'a', encoding='utf-8').write(addition)
    print('6. Legal AI updated with precedent search + evidence analysis')

# ── 6. Update law routes with new features ────────────────────────────────
law_routes_path = os.path.join(BACK, 'app', 'api', 'routes', 'law_routes.py')
content = open(law_routes_path, encoding='utf-8').read()

if 'precedent' not in content:
    addition = '''
class PrecedentRequest(BaseModel):
    matter_type: str
    facts: str
    court: Optional[str] = ""

class EvidenceRequest(BaseModel):
    matter_id: Optional[int] = None
    evidence_list: list
    matter_type: str

@law_router.post("/precedent-search")
def search_precedents(data: PrecedentRequest, u: User = Depends(get_current_user)):
    from app.services.ai.legal_ai import precedent_search
    result = precedent_search(data.matter_type, data.facts, data.court or "")
    return {"result": result, "matter_type": data.matter_type}

@law_router.post("/analyze-evidence")
def analyze_evidence_list(data: EvidenceRequest, u: User = Depends(get_current_user)):
    from app.services.ai.legal_ai import analyze_evidence
    result = analyze_evidence(data.evidence_list, data.matter_type)
    return {"result": result}

@law_router.get("/matters/{mid}/generate-invoice")
def generate_matter_invoice(mid: int, db: Session = Depends(get_db), u: User = Depends(get_current_user)):
    m = chk_matter(mid, u.id, db)
    entries = [e for e in m.time_entries if not e.is_billed]
    if not entries:
        return {"total_amount": 0, "message": "No unbilled entries"}
    total_hours = sum(e.hours for e in entries)
    total_amount = sum(e.amount or (e.hours * e.rate_per_hour) for e in entries)
    gst = total_amount * 0.18
    return {
        "matter_number": m.matter_number,
        "client_name": m.client_name,
        "total_hours": round(total_hours, 1),
        "subtotal": round(total_amount, 2),
        "gst_18pct": round(gst, 2),
        "grand_total": round(total_amount + gst, 2),
        "entries_count": len(entries),
    }

@law_router.get("/retainers")
def list_retainers(db: Session = Depends(get_db), u: User = Depends(get_current_user)):
    matters = db.query(Matter).filter(Matter.ca_user_id == u.id, Matter.is_active == True).all()
    result = []
    for m in matters:
        total = sum(e.amount or 0 for e in m.time_entries)
        billed = sum(e.amount or 0 for e in m.time_entries if e.is_billed)
        result.append({
            "matter_id": m.id,
            "matter_number": m.matter_number,
            "client_name": m.client_name,
            "total_value": round(total, 2),
            "billed": round(billed, 2),
            "outstanding": round(total - billed, 2),
        })
    return result
'''
    open(law_routes_path, 'a', encoding='utf-8').write(addition)
    print('7. Law routes updated with precedent search, evidence analysis, invoice generator, retainers')

print('\n' + '='*50)
print('ALL BACKEND FEATURES BUILT!')
print('='*50)
print('Restart backend: uvicorn main:app --port 8000')
