import os

# ── Law Firm Models ────────────────────────────────────────────────────────
os.makedirs('app/models', exist_ok=True)
f = open('app/models/law.py', 'w')
f.write('from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Text, ForeignKey, Date, Enum\n')
f.write('from sqlalchemy.orm import relationship\n')
f.write('from sqlalchemy.sql import func\n')
f.write('from app.db.database import Base\n')
f.write('import enum\n\n')
f.write('class MatterStatus(str, enum.Enum):\n')
f.write('    ACTIVE = "active"\n')
f.write('    PENDING = "pending"\n')
f.write('    URGENT = "urgent"\n')
f.write('    CLOSED = "closed"\n')
f.write('    DISCOVERY = "discovery"\n\n')
f.write('class Matter(Base):\n')
f.write('    __tablename__ = "matters"\n')
f.write('    id = Column(Integer, primary_key=True, index=True)\n')
f.write('    ca_user_id = Column(Integer, ForeignKey("users.id"), nullable=False)\n')
f.write('    client_id = Column(Integer, ForeignKey("clients.id"), nullable=True)\n')
f.write('    matter_number = Column(String(50), unique=True, index=True)\n')
f.write('    title = Column(String(500), nullable=False)\n')
f.write('    practice_area = Column(String(100))\n')
f.write('    court = Column(String(200))\n')
f.write('    judge = Column(String(200))\n')
f.write('    status = Column(Enum(MatterStatus), default=MatterStatus.PENDING)\n')
f.write('    filed_date = Column(Date)\n')
f.write('    next_hearing = Column(Date)\n')
f.write('    client_name = Column(String(255))\n')
f.write('    opposite_party = Column(String(255))\n')
f.write('    brief = Column(Text)\n')
f.write('    assigned_to = Column(String(255))\n')
f.write('    relief_sought = Column(Text)\n')
f.write('    is_active = Column(Boolean, default=True)\n')
f.write('    created_at = Column(DateTime(timezone=True), server_default=func.now())\n')
f.write('    updated_at = Column(DateTime(timezone=True), onupdate=func.now())\n')
f.write('    hearings = relationship("CourtHearing", back_populates="matter", cascade="all, delete-orphan")\n')
f.write('    time_entries = relationship("TimeEntry", back_populates="matter", cascade="all, delete-orphan")\n\n')
f.write('class CourtHearing(Base):\n')
f.write('    __tablename__ = "court_hearings"\n')
f.write('    id = Column(Integer, primary_key=True, index=True)\n')
f.write('    matter_id = Column(Integer, ForeignKey("matters.id"), nullable=False)\n')
f.write('    hearing_date = Column(Date, nullable=False)\n')
f.write('    hearing_time = Column(String(20))\n')
f.write('    court = Column(String(200))\n')
f.write('    purpose = Column(String(200))\n')
f.write('    notes = Column(Text)\n')
f.write('    is_attended = Column(Boolean, default=False)\n')
f.write('    reminder_sent = Column(Boolean, default=False)\n')
f.write('    outcome = Column(Text)\n')
f.write('    created_at = Column(DateTime(timezone=True), server_default=func.now())\n')
f.write('    matter = relationship("Matter", back_populates="hearings")\n\n')
f.write('class TimeEntry(Base):\n')
f.write('    __tablename__ = "time_entries"\n')
f.write('    id = Column(Integer, primary_key=True, index=True)\n')
f.write('    matter_id = Column(Integer, ForeignKey("matters.id"), nullable=False)\n')
f.write('    ca_user_id = Column(Integer, ForeignKey("users.id"), nullable=False)\n')
f.write('    entry_date = Column(Date, nullable=False)\n')
f.write('    hours = Column(Float, nullable=False)\n')
f.write('    rate_per_hour = Column(Float, nullable=False)\n')
f.write('    amount = Column(Float)\n')
f.write('    description = Column(Text)\n')
f.write('    is_billed = Column(Boolean, default=False)\n')
f.write('    invoice_id = Column(Integer, nullable=True)\n')
f.write('    created_at = Column(DateTime(timezone=True), server_default=func.now())\n')
f.write('    matter = relationship("Matter", back_populates="time_entries")\n\n')
f.write('class LegalDocument(Base):\n')
f.write('    __tablename__ = "legal_documents"\n')
f.write('    id = Column(Integer, primary_key=True, index=True)\n')
f.write('    matter_id = Column(Integer, ForeignKey("matters.id"), nullable=True)\n')
f.write('    ca_user_id = Column(Integer, ForeignKey("users.id"), nullable=False)\n')
f.write('    doc_type = Column(String(100))\n')
f.write('    title = Column(String(500))\n')
f.write('    content = Column(Text)\n')
f.write('    client_name = Column(String(255))\n')
f.write('    opposite_party = Column(String(255))\n')
f.write('    jurisdiction = Column(String(200))\n')
f.write('    ai_generated = Column(Boolean, default=True)\n')
f.write('    created_at = Column(DateTime(timezone=True), server_default=func.now())\n')
f.write('    updated_at = Column(DateTime(timezone=True), onupdate=func.now())\n\n')
f.write('class ContractAnalysis(Base):\n')
f.write('    __tablename__ = "contract_analyses"\n')
f.write('    id = Column(Integer, primary_key=True, index=True)\n')
f.write('    ca_user_id = Column(Integer, ForeignKey("users.id"), nullable=False)\n')
f.write('    matter_id = Column(Integer, ForeignKey("matters.id"), nullable=True)\n')
f.write('    filename = Column(String(500))\n')
f.write('    risk_score = Column(Float)\n')
f.write('    risk_level = Column(String(20))\n')
f.write('    summary = Column(Text)\n')
f.write('    red_flags = Column(Text)\n')
f.write('    clause_analysis = Column(Text)\n')
f.write('    recommendations = Column(Text)\n')
f.write('    created_at = Column(DateTime(timezone=True), server_default=func.now())\n')
f.close()
print('Law models created')

# ── Law AI Service ────────────────────────────────────────────────────────
os.makedirs('app/services/ai', exist_ok=True)
f = open('app/services/ai/legal_ai.py', 'w')
f.write('import json, logging\n')
f.write('from app.core.config import settings\n')
f.write('logger = logging.getLogger(__name__)\n\n')
f.write('try:\n')
f.write('    from openai import OpenAI\n')
f.write('    client = OpenAI(api_key=settings.OPENAI_API_KEY) if settings.OPENAI_API_KEY else None\n')
f.write('    AI_OK = bool(settings.OPENAI_API_KEY)\n')
f.write('except:\n')
f.write('    client = None\n')
f.write('    AI_OK = False\n\n')
f.write('def _call(system, user, json_mode=False):\n')
f.write('    if not AI_OK or not client:\n')
f.write('        return json.dumps({"error":"OpenAI API key not configured"}) if json_mode else "OpenAI API key not configured. Add OPENAI_API_KEY to .env"\n')
f.write('    try:\n')
f.write('        kwargs = {"model": settings.LLM_MODEL, "messages": [{"role":"system","content":system},{"role":"user","content":user}], "max_tokens":2000, "temperature":0.2}\n')
f.write('        if json_mode: kwargs["response_format"] = {"type":"json_object"}\n')
f.write('        r = client.chat.completions.create(**kwargs)\n')
f.write('        return r.choices[0].message.content\n')
f.write('    except Exception as e:\n')
f.write('        logger.error(f"AI error: {e}")\n')
f.write('        return json.dumps({"error":str(e)}) if json_mode else f"AI error: {e}"\n\n')
f.write('TEMPLATES = {\n')
f.write('    "Legal Notice": """Draft a formal Indian Legal Notice. Include:\n- Sender/Advocate details placeholder\n- Date\n- Recipient address\n- Subject line\n- Numbered facts/paragraphs\n- Clear demand with 15-day response period\n- Consequences of non-compliance\n- Signature block\nUse formal legal language appropriate for Indian courts.""",\n')
f.write('    "Service Agreement": "Draft a comprehensive Service Agreement under Indian law with: parties, scope, payment terms, IP ownership, confidentiality, termination, dispute resolution via arbitration, governing law.",\n')
f.write('    "NDA": "Draft a Non-Disclosure Agreement under Indian law with: definition of confidential information, obligations, exclusions, 3-year term, remedies for breach, governing law.",\n')
f.write('    "Plaint": "Draft a Civil Plaint for Indian District Court with: court name, plaintiff/defendant details, cause of action, facts, prayer/relief sought, verification.",\n')
f.write('    "Affidavit": "Draft an Affidavit for Indian court/authority with: deponent details, sworn statement, numbered paragraphs, verification clause.",\n')
f.write('    "Demand Notice": "Draft a Demand Notice under Section 138 NI Act for dishonoured cheque with: cheque details, dishonour details, 15-day demand, legal consequences.",\n')
f.write('    "Legal Opinion": "Draft a structured Legal Opinion with: facts, legal issues, analysis with case citations, conclusion and recommendations.",\n')
f.write('    "Rent Agreement": "Draft a Rent Agreement under Indian law with: parties, property description, rent, deposit, duration, termination, maintenance obligations.",\n')
f.write('    "Employment Contract": "Draft an Employment Contract under Indian labour law with: designation, CTC, probation, confidentiality, IP assignment, termination notice.",\n')
f.write('    "Power of Attorney": "Draft a Power of Attorney under Indian law with: principal, attorney, specific powers granted, duration, revocation clause.",\n')
f.write('}\n\n')
f.write('def generate_legal_document(doc_type, client_name, opposite_party, subject, jurisdiction, relief, extra=""):\n')
f.write('    template = TEMPLATES.get(doc_type, TEMPLATES["Legal Notice"])\n')
f.write('    system = f"""You are a senior Indian advocate drafting legal documents. {template}\nAlways use formal legal language. Include all standard clauses. Make it complete and ready to use."""\n')
f.write('    user = f"""Draft a {doc_type} with these details:\n\nClient/Party: {client_name}\nOpposite Party: {opposite_party}\nMatter/Subject: {subject}\nJurisdiction: {jurisdiction}\nRelief Sought: {relief}\nAdditional Details: {extra}\n\nGenerate the complete document."""\n')
f.write('    return _call(system, user)\n\n')
f.write('def analyze_contract_text(text):\n')
f.write('    system = """You are an expert Indian contract lawyer. Analyze the contract and return JSON:\n{\n  "risk_score": 1-10,\n  "risk_level": "low/medium/high",\n  "summary": "2-3 sentence summary",\n  "red_flags": ["flag1", "flag2"],\n  "clause_analysis": [\n    {"clause": "name", "risk": "high/medium/low", "description": "issue", "recommendation": "fix"}\n  ],\n  "missing_clauses": ["clause1"],\n  "recommendations": ["rec1", "rec2"]\n}"""\n')
f.write('    user = f"Analyze this contract:\\n\\n{text[:4000]}"\n')
f.write('    result = _call(system, user, json_mode=True)\n')
f.write('    try: return json.loads(result)\n')
f.write('    except: return {"risk_score":5,"risk_level":"medium","summary":"Unable to analyze","red_flags":[],"clause_analysis":[],"recommendations":[]}\n\n')
f.write('def legal_research(query, court_filter=""):\n')
f.write('    system = """You are a senior Indian advocate with expertise in Indian law. Provide legal research with:\n1. Relevant Supreme Court and High Court judgments\n2. Applicable sections of law\n3. Current legal position\n4. Practical advice\nFormat clearly with case citations."""\n')
f.write('    user = f"Research query: {query}\\nCourt filter: {court_filter}\\n\\nProvide relevant case law and legal analysis."\n')
f.write('    return _call(system, user)\n')
f.close()
print('Legal AI service created')

# ── Law Routes ────────────────────────────────────────────────────────────
f = open('app/api/routes/law_routes.py', 'w')
f.write('from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks\n')
f.write('from sqlalchemy.orm import Session\n')
f.write('from sqlalchemy import func\n')
f.write('from pydantic import BaseModel\n')
f.write('from typing import Optional, List\n')
f.write('from datetime import date, datetime\n')
f.write('from app.db.database import get_db\n')
f.write('from app.models.law import Matter, CourtHearing, TimeEntry, LegalDocument, ContractAnalysis, MatterStatus\n')
f.write('from app.models import User\n')
f.write('from app.core.security import get_current_user\n')
f.write('from app.services.ai.legal_ai import generate_legal_document, analyze_contract_text, legal_research\n\n')
f.write('law_router = APIRouter(prefix="/law", tags=["Law Firm"])\n\n')

# Pydantic models
f.write('class MatterCreate(BaseModel):\n')
f.write('    title: str\n')
f.write('    practice_area: Optional[str] = None\n')
f.write('    court: Optional[str] = None\n')
f.write('    client_name: Optional[str] = None\n')
f.write('    opposite_party: Optional[str] = None\n')
f.write('    brief: Optional[str] = None\n')
f.write('    assigned_to: Optional[str] = None\n')
f.write('    filed_date: Optional[date] = None\n')
f.write('    next_hearing: Optional[date] = None\n')
f.write('    status: Optional[str] = "pending"\n')
f.write('    relief_sought: Optional[str] = None\n\n')
f.write('class HearingCreate(BaseModel):\n')
f.write('    matter_id: int\n')
f.write('    hearing_date: date\n')
f.write('    hearing_time: Optional[str] = None\n')
f.write('    court: Optional[str] = None\n')
f.write('    purpose: Optional[str] = None\n')
f.write('    notes: Optional[str] = None\n\n')
f.write('class TimeEntryCreate(BaseModel):\n')
f.write('    matter_id: int\n')
f.write('    entry_date: date\n')
f.write('    hours: float\n')
f.write('    rate_per_hour: float\n')
f.write('    description: Optional[str] = None\n\n')
f.write('class DraftRequest(BaseModel):\n')
f.write('    doc_type: str\n')
f.write('    client_name: str\n')
f.write('    opposite_party: Optional[str] = ""\n')
f.write('    subject: str\n')
f.write('    jurisdiction: Optional[str] = ""\n')
f.write('    relief: Optional[str] = ""\n')
f.write('    matter_id: Optional[int] = None\n\n')
f.write('class ResearchRequest(BaseModel):\n')
f.write('    query: str\n')
f.write('    court_filter: Optional[str] = ""\n\n')

# Helper
f.write('def gen_matter_num(db):\n')
f.write('    count = db.query(func.count(Matter.id)).scalar() or 0\n')
f.write('    return f"MAT-{datetime.now().year}-{count+1:03d}"\n\n')
f.write('def chk_matter(matter_id, user_id, db):\n')
f.write('    m = db.query(Matter).filter(Matter.id==matter_id, Matter.ca_user_id==user_id, Matter.is_active==True).first()\n')
f.write('    if not m: raise HTTPException(status_code=404, detail="Matter not found")\n')
f.write('    return m\n\n')

# Matter routes
f.write('@law_router.get("/matters")\n')
f.write('def list_matters(status: Optional[str]=None, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    q = db.query(Matter).filter(Matter.ca_user_id==u.id, Matter.is_active==True)\n')
f.write('    if status: q = q.filter(Matter.status==status)\n')
f.write('    matters = q.order_by(Matter.created_at.desc()).all()\n')
f.write('    return [{"id":m.id,"matter_number":m.matter_number,"title":m.title,"practice_area":m.practice_area,"court":m.court,"status":m.status.value if m.status else "pending","client_name":m.client_name,"opposite_party":m.opposite_party,"next_hearing":str(m.next_hearing) if m.next_hearing else None,"assigned_to":m.assigned_to,"created_at":str(m.created_at)} for m in matters]\n\n')
f.write('@law_router.post("/matters", status_code=201)\n')
f.write('def create_matter(data: MatterCreate, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    m = Matter(**data.model_dump(exclude={"status"}), ca_user_id=u.id, matter_number=gen_matter_num(db))\n')
f.write('    if data.status:\n')
f.write('        try: m.status = MatterStatus(data.status)\n')
f.write('        except: m.status = MatterStatus.PENDING\n')
f.write('    db.add(m); db.commit(); db.refresh(m)\n')
f.write('    return {"id":m.id,"matter_number":m.matter_number,"title":m.title,"status":m.status.value}\n\n')
f.write('@law_router.get("/matters/{mid}")\n')
f.write('def get_matter(mid: int, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    m = chk_matter(mid, u.id, db)\n')
f.write('    hearings = [{"id":h.id,"hearing_date":str(h.hearing_date),"hearing_time":h.hearing_time,"court":h.court,"purpose":h.purpose,"is_attended":h.is_attended} for h in m.hearings]\n')
f.write('    entries = [{"id":e.id,"entry_date":str(e.entry_date),"hours":e.hours,"rate_per_hour":e.rate_per_hour,"amount":e.amount,"description":e.description,"is_billed":e.is_billed} for e in m.time_entries]\n')
f.write('    return {"id":m.id,"matter_number":m.matter_number,"title":m.title,"practice_area":m.practice_area,"court":m.court,"status":m.status.value if m.status else "pending","client_name":m.client_name,"opposite_party":m.opposite_party,"brief":m.brief,"next_hearing":str(m.next_hearing) if m.next_hearing else None,"filed_date":str(m.filed_date) if m.filed_date else None,"assigned_to":m.assigned_to,"relief_sought":m.relief_sought,"hearings":hearings,"time_entries":entries}\n\n')
f.write('@law_router.put("/matters/{mid}")\n')
f.write('def update_matter(mid: int, data: dict, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    m = chk_matter(mid, u.id, db)\n')
f.write('    for k,v in data.items():\n')
f.write('        if k == "status":\n')
f.write('            try: setattr(m, k, MatterStatus(v))\n')
f.write('            except: pass\n')
f.write('        elif hasattr(m, k): setattr(m, k, v)\n')
f.write('    db.commit()\n')
f.write('    return {"updated": True}\n\n')
f.write('@law_router.delete("/matters/{mid}")\n')
f.write('def delete_matter(mid: int, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    m = chk_matter(mid, u.id, db)\n')
f.write('    m.is_active = False; db.commit()\n')
f.write('    return {"deleted": True}\n\n')

# Hearing routes
f.write('@law_router.get("/hearings")\n')
f.write('def list_hearings(days: int=30, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    from datetime import timedelta\n')
f.write('    today = date.today()\n')
f.write('    deadline = today + timedelta(days=days)\n')
f.write('    matter_ids = [m.id for m in db.query(Matter).filter(Matter.ca_user_id==u.id, Matter.is_active==True).all()]\n')
f.write('    if not matter_ids: return []\n')
f.write('    hs = db.query(CourtHearing).filter(CourtHearing.matter_id.in_(matter_ids), CourtHearing.hearing_date>=today, CourtHearing.hearing_date<=deadline).order_by(CourtHearing.hearing_date).all()\n')
f.write('    result = []\n')
f.write('    for h in hs:\n')
f.write('        m = db.query(Matter).filter(Matter.id==h.matter_id).first()\n')
f.write('        days_left = (h.hearing_date - today).days\n')
f.write('        result.append({"id":h.id,"matter_id":h.matter_id,"matter_number":m.matter_number if m else "","matter_title":m.title if m else "","client_name":m.client_name if m else "","hearing_date":str(h.hearing_date),"hearing_time":h.hearing_time,"court":h.court or (m.court if m else ""),"purpose":h.purpose,"is_attended":h.is_attended,"days_left":days_left,"is_today":days_left==0,"is_urgent":days_left<=3})\n')
f.write('    return result\n\n')
f.write('@law_router.post("/hearings", status_code=201)\n')
f.write('def add_hearing(data: HearingCreate, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    chk_matter(data.matter_id, u.id, db)\n')
f.write('    h = CourtHearing(**data.model_dump())\n')
f.write('    db.add(h); db.commit(); db.refresh(h)\n')
f.write('    m = db.query(Matter).filter(Matter.id==data.matter_id).first()\n')
f.write('    if m and (not m.next_hearing or h.hearing_date < m.next_hearing):\n')
f.write('        m.next_hearing = h.hearing_date; db.commit()\n')
f.write('    return {"id":h.id,"hearing_date":str(h.hearing_date)}\n\n')
f.write('@law_router.put("/hearings/{hid}/attend")\n')
f.write('def mark_attended(hid: int, data: dict={}, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    h = db.query(CourtHearing).filter(CourtHearing.id==hid).first()\n')
f.write('    if not h: raise HTTPException(status_code=404, detail="Hearing not found")\n')
f.write('    h.is_attended = True\n')
f.write('    h.outcome = data.get("outcome", "")\n')
f.write('    db.commit()\n')
f.write('    return {"attended": True}\n\n')

# Time entry routes
f.write('@law_router.get("/time-entries")\n')
f.write('def list_time(matter_id: Optional[int]=None, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    matter_ids = [m.id for m in db.query(Matter).filter(Matter.ca_user_id==u.id).all()]\n')
f.write('    q = db.query(TimeEntry).filter(TimeEntry.matter_id.in_(matter_ids))\n')
f.write('    if matter_id: q = q.filter(TimeEntry.matter_id==matter_id)\n')
f.write('    entries = q.order_by(TimeEntry.entry_date.desc()).all()\n')
f.write('    result = []\n')
f.write('    for e in entries:\n')
f.write('        m = db.query(Matter).filter(Matter.id==e.matter_id).first()\n')
f.write('        result.append({"id":e.id,"matter_id":e.matter_id,"matter_number":m.matter_number if m else "","matter_title":m.title if m else "","entry_date":str(e.entry_date),"hours":e.hours,"rate_per_hour":e.rate_per_hour,"amount":e.amount or round(e.hours*e.rate_per_hour,2),"description":e.description,"is_billed":e.is_billed})\n')
f.write('    return result\n\n')
f.write('@law_router.post("/time-entries", status_code=201)\n')
f.write('def add_time(data: TimeEntryCreate, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    chk_matter(data.matter_id, u.id, db)\n')
f.write('    e = TimeEntry(**data.model_dump(), ca_user_id=u.id, amount=round(data.hours*data.rate_per_hour, 2))\n')
f.write('    db.add(e); db.commit(); db.refresh(e)\n')
f.write('    return {"id":e.id,"amount":e.amount}\n\n')
f.write('@law_router.put("/time-entries/{eid}/bill")\n')
f.write('def mark_billed(eid: int, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    e = db.query(TimeEntry).filter(TimeEntry.id==eid, TimeEntry.ca_user_id==u.id).first()\n')
f.write('    if not e: raise HTTPException(status_code=404, detail="Entry not found")\n')
f.write('    e.is_billed = True; db.commit()\n')
f.write('    return {"billed": True}\n\n')
f.write('@law_router.get("/billing-summary")\n')
f.write('def billing_summary(db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    matter_ids = [m.id for m in db.query(Matter).filter(Matter.ca_user_id==u.id).all()]\n')
f.write('    entries = db.query(TimeEntry).filter(TimeEntry.matter_id.in_(matter_ids)).all() if matter_ids else []\n')
f.write('    total_hours = sum(e.hours for e in entries)\n')
f.write('    total_billed = sum(e.amount or 0 for e in entries if e.is_billed)\n')
f.write('    total_unbilled = sum(e.amount or 0 for e in entries if not e.is_billed)\n')
f.write('    return {"total_hours":round(total_hours,1),"total_billed":round(total_billed,2),"total_unbilled":round(total_unbilled,2),"total_entries":len(entries)}\n\n')

# AI Drafting routes
f.write('@law_router.post("/draft")\n')
f.write('def draft_document(data: DraftRequest, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    content = generate_legal_document(data.doc_type, data.client_name, data.opposite_party or "", data.subject, data.jurisdiction or "", data.relief or "")\n')
f.write('    doc = LegalDocument(ca_user_id=u.id, matter_id=data.matter_id, doc_type=data.doc_type, title=f"{data.doc_type} — {data.client_name}", content=content, client_name=data.client_name, opposite_party=data.opposite_party, jurisdiction=data.jurisdiction, ai_generated=True)\n')
f.write('    db.add(doc); db.commit(); db.refresh(doc)\n')
f.write('    return {"id":doc.id,"content":content,"title":doc.title}\n\n')
f.write('@law_router.get("/drafts")\n')
f.write('def list_drafts(db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    docs = db.query(LegalDocument).filter(LegalDocument.ca_user_id==u.id).order_by(LegalDocument.created_at.desc()).limit(20).all()\n')
f.write('    return [{"id":d.id,"doc_type":d.doc_type,"title":d.title,"client_name":d.client_name,"created_at":str(d.created_at)} for d in docs]\n\n')
f.write('@law_router.get("/drafts/{did}")\n')
f.write('def get_draft(did: int, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    d = db.query(LegalDocument).filter(LegalDocument.id==did, LegalDocument.ca_user_id==u.id).first()\n')
f.write('    if not d: raise HTTPException(status_code=404, detail="Draft not found")\n')
f.write('    return {"id":d.id,"doc_type":d.doc_type,"title":d.title,"content":d.content,"client_name":d.client_name,"created_at":str(d.created_at)}\n\n')

# Contract analysis
f.write('@law_router.post("/analyze-contract")\n')
f.write('async def analyze_contract(data: dict, db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    text = data.get("text", "")\n')
f.write('    if not text: raise HTTPException(status_code=400, detail="Contract text required")\n')
f.write('    result = analyze_contract_text(text)\n')
f.write('    ca = ContractAnalysis(ca_user_id=u.id, matter_id=data.get("matter_id"), filename=data.get("filename","contract.pdf"), risk_score=result.get("risk_score",5), risk_level=result.get("risk_level","medium"), summary=result.get("summary",""), red_flags=str(result.get("red_flags",[])), clause_analysis=str(result.get("clause_analysis",[])), recommendations=str(result.get("recommendations",[])))\n')
f.write('    db.add(ca); db.commit()\n')
f.write('    return result\n\n')

# Legal research
f.write('@law_router.post("/research")\n')
f.write('def research(data: ResearchRequest, u: User=Depends(get_current_user)):\n')
f.write('    result = legal_research(data.query, data.court_filter or "")\n')
f.write('    return {"result": result, "query": data.query}\n\n')

# Law dashboard
f.write('@law_router.get("/dashboard")\n')
f.write('def law_dashboard(db: Session=Depends(get_db), u: User=Depends(get_current_user)):\n')
f.write('    from datetime import timedelta\n')
f.write('    today = date.today()\n')
f.write('    matters = db.query(Matter).filter(Matter.ca_user_id==u.id, Matter.is_active==True).all()\n')
f.write('    matter_ids = [m.id for m in matters]\n')
f.write('    urgent = len([m for m in matters if m.status and m.status.value == "urgent"])\n')
f.write('    week_hearings = db.query(CourtHearing).filter(CourtHearing.matter_id.in_(matter_ids), CourtHearing.hearing_date>=today, CourtHearing.hearing_date<=today+timedelta(days=7)).count() if matter_ids else 0\n')
f.write('    today_hearings = db.query(CourtHearing).filter(CourtHearing.matter_id.in_(matter_ids), CourtHearing.hearing_date==today).count() if matter_ids else 0\n')
f.write('    entries = db.query(TimeEntry).filter(TimeEntry.matter_id.in_(matter_ids)).all() if matter_ids else []\n')
f.write('    billed = sum(e.amount or 0 for e in entries if e.is_billed)\n')
f.write('    return {"total_matters":len(matters),"urgent_matters":urgent,"week_hearings":week_hearings,"today_hearings":today_hearings,"total_billed":round(billed,2),"total_hours":round(sum(e.hours for e in entries),1)}\n')
f.close()
print('Law routes created')

# Update main.py
content = open('main.py').read()
changes = 0
if 'law_router' not in content:
    old1 = '    from app.api.routes.routes import ('
    new1 = '    from app.api.routes.law_routes import law_router\n    from app.api.routes.routes import ('
    content = content.replace(old1, new1)
    # find last include_router and add after
    last = '    app.include_router(alert_router, prefix="/api/v1")'
    if last in content:
        content = content.replace(last, last + '\n    app.include_router(law_router, prefix="/api/v1")')
    else:
        old2 = '    app.include_router(chat_router, prefix="/api/v1")'
        content = content.replace(old2, old2 + '\n    app.include_router(law_router, prefix="/api/v1")')
    open('main.py', 'w').write(content)
    changes = 1
    print('main.py updated with law_router')
else:
    print('law_router already in main.py')

# Create law tables
from app.db.database import engine, Base
from app.models.law import Matter, CourtHearing, TimeEntry, LegalDocument, ContractAnalysis
Base.metadata.create_all(bind=engine)
print('Law tables created in database')

# Seed sample matters
from app.db.database import SessionLocal
from app.models.law import Matter, MatterStatus, CourtHearing
from datetime import date, timedelta
db = SessionLocal()
try:
    existing = db.query(Matter).first()
    if not existing:
        from app.models import User
        user = db.query(User).first()
        if user:
            matters_data = [
                {"title":"Ramesh Gupta vs ABC Builders — Property Dispute","practice_area":"Civil","court":"High Court Delhi","client_name":"Ramesh Gupta","opposite_party":"ABC Builders Pvt Ltd","status":MatterStatus.ACTIVE,"brief":"Property dispute regarding flat purchase and refund of advance","relief_sought":"Refund of ₹15,00,000 with 18% interest"},
                {"title":"XYZ Corp Ltd vs Vendor — Contract Breach","practice_area":"Corporate","court":"District Court Mumbai","client_name":"XYZ Corp Ltd","opposite_party":"TechSupply Pvt Ltd","status":MatterStatus.DISCOVERY,"brief":"Breach of service agreement"},
                {"title":"Priya Holdings — Trademark Infringement","practice_area":"IP / Trademark","court":"IP Appellate Board","client_name":"Priya Holdings","opposite_party":"Copycat Brands Ltd","status":MatterStatus.URGENT,"brief":"Trademark infringement — similar brand name"},
                {"title":"Arun Mehta vs Employer — Wrongful Termination","practice_area":"Labour / Employment","court":"Labour Court Chennai","client_name":"Arun Mehta","opposite_party":"Mega Corp India","status":MatterStatus.ACTIVE,"brief":"Wrongful termination without notice"},
                {"title":"StarTech Pvt Ltd — NCLT Merger Approval","practice_area":"Corporate","court":"NCLT Mumbai","client_name":"StarTech Pvt Ltd","opposite_party":"","status":MatterStatus.PENDING,"brief":"Merger approval application"},
            ]
            today = date.today()
            for i, md in enumerate(matters_data):
                m = Matter(ca_user_id=user.id, matter_number=f"MAT-2024-{i+1:03d}", **md)
                db.add(m)
                db.flush()
                h = CourtHearing(matter_id=m.id, hearing_date=today+timedelta(days=i*7+3), hearing_time="10:30 AM", court=m.court, purpose=["Final Arguments","Preliminary Hearing","Evidence Hearing","Conciliation","First Hearing"][i])
                db.add(h)
            db.commit()
            print('Sample matters seeded')
    else:
        print('Matters already exist — skipping seed')
finally:
    db.close()

print('\n✅ Law firm backend complete!')
print('Now run: uvicorn main:app --port 8000')