lines = [
    "from fastapi import APIRouter, Depends, HTTPException\n",
    "from sqlalchemy.orm import Session\n",
    "from app.db.database import get_db\n",
    "from app.models import User\n",
    "from app.schemas import UserCreate, TokenResponse, UserResponse\n",
    "from app.core.security import get_password_hash, verify_password, create_access_token, get_current_user\n",
    "from pydantic import BaseModel\n",
    "\n",
    "router = APIRouter(prefix='/auth', tags=['Authentication'])\n",
    "\n",
    "class LoginRequest(BaseModel):\n",
    "    email: str\n",
    "    password: str\n",
    "\n",
    "@router.post('/signup', response_model=TokenResponse)\n",
    "def signup(user_data: UserCreate, db: Session = Depends(get_db)):\n",
    "    existing = db.query(User).filter(User.email == user_data.email).first()\n",
    "    if existing:\n",
    "        raise HTTPException(status_code=400, detail='Email already registered')\n",
    "    user = User(\n",
    "        email=user_data.email,\n",
    "        full_name=user_data.full_name,\n",
    "        hashed_password=get_password_hash(user_data.password),\n",
    "        firm_name=user_data.firm_name,\n",
    "        phone=user_data.phone,\n",
    "        role=user_data.role,\n",
    "    )\n",
    "    db.add(user)\n",
    "    db.commit()\n",
    "    db.refresh(user)\n",
    "    token = create_access_token({'sub': str(user.id)})\n",
    "    return TokenResponse(access_token=token, user=UserResponse.model_validate(user))\n",
    "\n",
    "@router.post('/login', response_model=TokenResponse)\n",
    "def login(credentials: LoginRequest, db: Session = Depends(get_db)):\n",
    "    user = db.query(User).filter(User.email == credentials.email).first()\n",
    "    if not user or not verify_password(credentials.password, user.hashed_password):\n",
    "        raise HTTPException(status_code=401, detail='Invalid email or password')\n",
    "    if not user.is_active:\n",
    "        raise HTTPException(status_code=403, detail='Account is inactive')\n",
    "    token = create_access_token({'sub': str(user.id)})\n",
    "    return TokenResponse(access_token=token, user=UserResponse.model_validate(user))\n",
    "\n",
    "@router.get('/me', response_model=UserResponse)\n",
    "def get_me(current_user: User = Depends(get_current_user)):\n",
    "    return current_user\n",
]

with open('app/api/routes/auth.py', 'w') as f:
    f.writelines(lines)
print('auth.py fixed')