import os

# Create directories
os.makedirs('app/services/gst', exist_ok=True)
os.makedirs('app/services/email', exist_ok=True)

# GST Engine
open('app/services/gst/__init__.py', 'w').write('')
open('app/services/email/__init__.py', 'w').write('')

gst_engine = open('app/services/gst/gst_engine.py', 'w')
gst_engine.write('import re\n')
gst_engine.write('from sqlalchemy.orm import Session\n')
gst_engine.write('from app.models import Invoice, GSTMismatch\n')
gst_engine.write('\n')
gst_engine.write('GSTIN_RE = re.compile(r"^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}Z[A-Z\\d]{1}$")\n')
gst_engine.write('\n')
gst_engine.write('def validate_gstin(g):\n')
gst_engine.write('    return bool(g and GSTIN_RE.match(g.upper().strip()))\n')
gst_engine.write('\n')
gst_engine.write('def get_gstin_state(gstin):\n')
gst_engine.write('    STATES = {"01":"J&K","02":"HP","03":"Punjab","04":"Chandigarh","05":"Uttarakhand","06":"Haryana","07":"Delhi","08":"Rajasthan","09":"UP","10":"Bihar","18":"Assam","19":"WB","20":"Jharkhand","21":"Odisha","22":"CG","23":"MP","24":"Gujarat","27":"Maharashtra","29":"Karnataka","32":"Kerala","33":"TN","36":"Telangana"}\n')
gst_engine.write('    return STATES.get(gstin[:2], "Unknown") if gstin and len(gstin) >= 2 else "Unknown"\n')
gst_engine.write('\n')
gst_engine.write('def run_gst_analysis(client_id, db):\n')
gst_engine.write('    invoices = db.query(Invoice).filter(Invoice.client_id == client_id).all()\n')
gst_engine.write('    issues = []\n')
gst_engine.write('    for inv in invoices:\n')
gst_engine.write('        if inv.vendor_gstin and not validate_gstin(inv.vendor_gstin):\n')
gst_engine.write('            issues.append({"invoice_id":inv.id,"type":"invalid_gstin","severity":"high","description":f"Invalid GSTIN: {inv.vendor_gstin}","vendor_gstin":inv.vendor_gstin,"invoice_number":inv.invoice_number})\n')
gst_engine.write('        if inv.taxable_amount and inv.taxable_amount > 0:\n')
gst_engine.write('            rate = (inv.cgst_rate or 0)+(inv.sgst_rate or 0)+(inv.igst_rate or 0)\n')
gst_engine.write('            expected = round(inv.taxable_amount * rate / 100, 2)\n')
gst_engine.write('            actual = round((inv.cgst_amount or 0)+(inv.sgst_amount or 0)+(inv.igst_amount or 0), 2)\n')
gst_engine.write('            if rate > 0 and abs(expected - actual) > 1.0:\n')
gst_engine.write('                issues.append({"invoice_id":inv.id,"type":"gst_calculation_error","severity":"medium","description":f"Expected Rs.{expected}, found Rs.{actual}","our_amount":actual,"portal_amount":expected,"difference":round(expected-actual,2),"invoice_number":inv.invoice_number})\n')
gst_engine.write('        if not inv.invoice_number:\n')
gst_engine.write('            issues.append({"invoice_id":inv.id,"type":"missing_invoice_number","severity":"low","description":"Invoice number missing","invoice_number":None})\n')
gst_engine.write('    for issue in issues:\n')
gst_engine.write('        from app.models import GSTMismatch\n')
gst_engine.write('        ex = db.query(GSTMismatch).filter(GSTMismatch.invoice_id==issue.get("invoice_id"),GSTMismatch.mismatch_type==issue["type"],GSTMismatch.is_resolved==False).first()\n')
gst_engine.write('        if not ex:\n')
gst_engine.write('            m = GSTMismatch(client_id=client_id,invoice_id=issue.get("invoice_id"),mismatch_type=issue["type"],description=issue["description"],our_amount=issue.get("our_amount"),portal_amount=issue.get("portal_amount"),difference=issue.get("difference"),vendor_gstin=issue.get("vendor_gstin"),invoice_number=issue.get("invoice_number"))\n')
gst_engine.write('            db.add(m)\n')
gst_engine.write('    db.commit()\n')
gst_engine.write('    sales = [i for i in invoices if i.invoice_type and i.invoice_type.value == "sale"]\n')
gst_engine.write('    purchases = [i for i in invoices if i.invoice_type and i.invoice_type.value == "purchase"]\n')
gst_engine.write('    output_gst = sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in sales)\n')
gst_engine.write('    input_gst = sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in purchases)\n')
gst_engine.write('    return {"total_invoices":len(invoices),"issues_found":len(issues),"output_gst":round(output_gst,2),"input_gst":round(input_gst,2),"net_payable":round(output_gst-input_gst,2),"issues":issues,"health":"good" if len(issues)==0 else "warning" if len(issues)<=3 else "critical"}\n')
gst_engine.write('\n')
gst_engine.write('def get_gst_mismatches(client_id, db):\n')
gst_engine.write('    return db.query(GSTMismatch).filter(GSTMismatch.client_id==client_id).order_by(GSTMismatch.created_at.desc()).all()\n')
gst_engine.write('\n')
gst_engine.write('def resolve_mismatch(mismatch_id, db):\n')
gst_engine.write('    from datetime import datetime\n')
gst_engine.write('    m = db.query(GSTMismatch).filter(GSTMismatch.id==mismatch_id).first()\n')
gst_engine.write('    if m:\n')
gst_engine.write('        m.is_resolved = True\n')
gst_engine.write('        m.resolved_at = datetime.utcnow()\n')
gst_engine.write('        db.commit()\n')
gst_engine.write('        return True\n')
gst_engine.write('    return False\n')
gst_engine.close()
print('GST engine created')

# GST Routes
f = open('app/api/routes/gst_routes.py', 'w')
f.write('from fastapi import APIRouter, Depends, HTTPException\n')
f.write('from sqlalchemy.orm import Session\n')
f.write('from app.db.database import get_db\n')
f.write('from app.models import Client, GSTMismatch, Invoice\n')
f.write('from app.core.security import get_current_user\n')
f.write('from app.services.gst.gst_engine import run_gst_analysis, get_gst_mismatches, resolve_mismatch, validate_gstin, get_gstin_state\n')
f.write('\n')
f.write('gst_router = APIRouter(prefix="/gst", tags=["GST Intelligence"])\n')
f.write('\n')
f.write('def verify_client(client_id, user_id, db):\n')
f.write('    c = db.query(Client).filter(Client.id==client_id, Client.ca_user_id==user_id).first()\n')
f.write('    if not c: raise HTTPException(status_code=404, detail="Client not found")\n')
f.write('    return c\n')
f.write('\n')
f.write('@gst_router.post("/client/{client_id}/analyze")\n')
f.write('def analyze_gst(client_id: int, db: Session=Depends(get_db), current_user=Depends(get_current_user)):\n')
f.write('    verify_client(client_id, current_user.id, db)\n')
f.write('    return run_gst_analysis(client_id, db)\n')
f.write('\n')
f.write('@gst_router.get("/client/{client_id}/mismatches")\n')
f.write('def list_mismatches(client_id: int, db: Session=Depends(get_db), current_user=Depends(get_current_user)):\n')
f.write('    verify_client(client_id, current_user.id, db)\n')
f.write('    mismatches = get_gst_mismatches(client_id, db)\n')
f.write('    return [{"id":m.id,"invoice_id":m.invoice_id,"invoice_number":m.invoice_number,"type":m.mismatch_type,"description":m.description,"severity":"high" if "gstin" in (m.mismatch_type or "") else "medium","our_amount":m.our_amount,"portal_amount":m.portal_amount,"difference":m.difference,"vendor_gstin":m.vendor_gstin,"is_resolved":m.is_resolved,"created_at":str(m.created_at)} for m in mismatches]\n')
f.write('\n')
f.write('@gst_router.put("/mismatches/{mismatch_id}/resolve")\n')
f.write('def resolve(mismatch_id: int, db: Session=Depends(get_db), current_user=Depends(get_current_user)):\n')
f.write('    return {"resolved": resolve_mismatch(mismatch_id, db)}\n')
f.write('\n')
f.write('@gst_router.post("/validate-gstin")\n')
f.write('def validate(data: dict, current_user=Depends(get_current_user)):\n')
f.write('    gstin = data.get("gstin", "")\n')
f.write('    valid = validate_gstin(gstin)\n')
f.write('    return {"gstin": gstin, "valid": valid, "state": get_gstin_state(gstin) if valid else None}\n')
f.write('\n')
f.write('@gst_router.get("/client/{client_id}/summary")\n')
f.write('def gst_summary(client_id: int, db: Session=Depends(get_db), current_user=Depends(get_current_user)):\n')
f.write('    verify_client(client_id, current_user.id, db)\n')
f.write('    invoices = db.query(Invoice).filter(Invoice.client_id==client_id).all()\n')
f.write('    from app.models import GSTMismatch\n')
f.write('    unresolved = db.query(GSTMismatch).filter(GSTMismatch.client_id==client_id, GSTMismatch.is_resolved==False).count()\n')
f.write('    sales = [i for i in invoices if i.invoice_type and i.invoice_type.value=="sale"]\n')
f.write('    purchases = [i for i in invoices if i.invoice_type and i.invoice_type.value=="purchase"]\n')
f.write('    output_gst = sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in sales)\n')
f.write('    input_gst = sum((i.cgst_amount or 0)+(i.sgst_amount or 0)+(i.igst_amount or 0) for i in purchases)\n')
f.write('    return {"total_invoices":len(invoices),"sale_invoices":len(sales),"purchase_invoices":len(purchases),"output_gst":round(output_gst,2),"input_gst":round(input_gst,2),"net_payable":round(output_gst-input_gst,2),"unresolved_mismatches":unresolved}\n')
f.close()
print('GST routes created')

# Email Service
f = open('app/services/email/email_service.py', 'w')
f.write('import smtplib, logging\n')
f.write('from email.mime.text import MIMEText\n')
f.write('from email.mime.multipart import MIMEMultipart\n')
f.write('from datetime import date, timedelta\n')
f.write('from app.core.config import settings\n')
f.write('logger = logging.getLogger(__name__)\n')
f.write('\n')
f.write('def send_email(to_email, subject, body):\n')
f.write('    if not settings.MAIL_USERNAME or not settings.MAIL_PASSWORD:\n')
f.write('        logger.warning("Email not configured")\n')
f.write('        return False\n')
f.write('    try:\n')
f.write('        msg = MIMEMultipart("alternative")\n')
f.write('        msg["Subject"] = subject\n')
f.write('        msg["From"] = settings.MAIL_FROM\n')
f.write('        msg["To"] = to_email\n')
f.write('        msg.attach(MIMEText(body, "html"))\n')
f.write('        with smtplib.SMTP(settings.MAIL_SERVER, settings.MAIL_PORT) as s:\n')
f.write('            s.ehlo(); s.starttls()\n')
f.write('            s.login(settings.MAIL_USERNAME, settings.MAIL_PASSWORD)\n')
f.write('            s.sendmail(settings.MAIL_FROM, to_email, msg.as_string())\n')
f.write('        return True\n')
f.write('    except Exception as e:\n')
f.write('        logger.error(f"Email failed: {e}")\n')
f.write('        return False\n')
f.write('\n')
f.write('def send_compliance_alerts(db):\n')
f.write('    from app.models import ComplianceItem, ComplianceStatus, Client, User\n')
f.write('    today = date.today()\n')
f.write('    sent = 0\n')
f.write('    for client in db.query(Client).filter(Client.is_active==True).all():\n')
f.write('        ca = db.query(User).filter(User.id==client.ca_user_id).first()\n')
f.write('        if not ca or not ca.email: continue\n')
f.write('        items = db.query(ComplianceItem).filter(ComplianceItem.client_id==client.id,ComplianceItem.status.in_([ComplianceStatus.PENDING,ComplianceStatus.OVERDUE]),ComplianceItem.due_date<=today+timedelta(days=7),ComplianceItem.reminder_sent==False).all()\n')
f.write('        if not items: continue\n')
f.write('        body = f"<h2>Compliance Alert for {client.company_name}</h2><p>{len(items)} deadline(s) due within 7 days. Please login to AI Copilot Pro to take action.</p>"\n')
f.write('        if send_email(ca.email, f"Compliance Alert - {client.company_name}", body):\n')
f.write('            for item in items: item.reminder_sent = True\n')
f.write('            db.commit()\n')
f.write('            sent += 1\n')
f.write('    return {"sent": sent}\n')
f.close()
print('Email service created')

# Org Models
os.makedirs('app/models', exist_ok=True)
f = open('app/models/organisation.py', 'w')
f.write('from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Enum\n')
f.write('from sqlalchemy.orm import relationship\n')
f.write('from sqlalchemy.sql import func\n')
f.write('from app.db.database import Base\n')
f.write('import enum\n')
f.write('\n')
f.write('class OrgRole(str, enum.Enum):\n')
f.write('    OWNER = "owner"\n')
f.write('    MANAGER = "manager"\n')
f.write('    STAFF = "staff"\n')
f.write('\n')
f.write('class Organisation(Base):\n')
f.write('    __tablename__ = "organisations"\n')
f.write('    id = Column(Integer, primary_key=True, index=True)\n')
f.write('    name = Column(String(255), nullable=False)\n')
f.write('    slug = Column(String(100), unique=True, index=True)\n')
f.write('    plan = Column(String(50), default="free")\n')
f.write('    is_active = Column(Boolean, default=True)\n')
f.write('    created_at = Column(DateTime(timezone=True), server_default=func.now())\n')
f.write('    members = relationship("OrgMember", back_populates="organisation", cascade="all, delete-orphan")\n')
f.write('\n')
f.write('class OrgMember(Base):\n')
f.write('    __tablename__ = "org_members"\n')
f.write('    id = Column(Integer, primary_key=True, index=True)\n')
f.write('    org_id = Column(Integer, ForeignKey("organisations.id"), nullable=False)\n')
f.write('    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)\n')
f.write('    role = Column(Enum(OrgRole), default=OrgRole.STAFF)\n')
f.write('    is_active = Column(Boolean, default=True)\n')
f.write('    joined_at = Column(DateTime(timezone=True), server_default=func.now())\n')
f.write('    organisation = relationship("Organisation", back_populates="members")\n')
f.write('\n')
f.write('class OrgInvite(Base):\n')
f.write('    __tablename__ = "org_invites"\n')
f.write('    id = Column(Integer, primary_key=True, index=True)\n')
f.write('    org_id = Column(Integer, ForeignKey("organisations.id"), nullable=False)\n')
f.write('    email = Column(String(255), nullable=False)\n')
f.write('    role = Column(Enum(OrgRole), default=OrgRole.STAFF)\n')
f.write('    token = Column(String(100), unique=True, index=True)\n')
f.write('    is_used = Column(Boolean, default=False)\n')
f.write('    expires_at = Column(DateTime(timezone=True))\n')
f.write('    created_at = Column(DateTime(timezone=True), server_default=func.now())\n')
f.close()
print('Org models created')

# Org Routes
f = open('app/api/routes/org_routes.py', 'w')
f.write('from fastapi import APIRouter, Depends, HTTPException\n')
f.write('from sqlalchemy.orm import Session\n')
f.write('from pydantic import BaseModel\n')
f.write('from typing import Optional\n')
f.write('import secrets, re\n')
f.write('from app.db.database import get_db\n')
f.write('from app.models.organisation import Organisation, OrgMember, OrgInvite, OrgRole\n')
f.write('from app.models import User\n')
f.write('from app.core.security import get_current_user, get_password_hash\n')
f.write('\n')
f.write('org_router = APIRouter(prefix="/org", tags=["Organisation"])\n')
f.write('\n')
f.write('class OrgCreate(BaseModel):\n')
f.write('    name: str\n')
f.write('\n')
f.write('class InviteCreate(BaseModel):\n')
f.write('    email: str\n')
f.write('    role: str = "staff"\n')
f.write('\n')
f.write('class AcceptInvite(BaseModel):\n')
f.write('    token: str\n')
f.write('    full_name: str\n')
f.write('    password: str\n')
f.write('\n')
f.write('def slugify(name):\n')
f.write('    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")\n')
f.write('\n')
f.write('@org_router.post("/create")\n')
f.write('def create_org(data: OrgCreate, db: Session=Depends(get_db), current_user: User=Depends(get_current_user)):\n')
f.write('    slug = slugify(data.name)\n')
f.write('    if db.query(Organisation).filter(Organisation.slug==slug).first():\n')
f.write('        slug = slug + "-" + secrets.token_hex(3)\n')
f.write('    org = Organisation(name=data.name, slug=slug)\n')
f.write('    db.add(org); db.flush()\n')
f.write('    db.add(OrgMember(org_id=org.id, user_id=current_user.id, role=OrgRole.OWNER))\n')
f.write('    db.commit(); db.refresh(org)\n')
f.write('    return {"id": org.id, "name": org.name, "slug": org.slug, "role": "owner"}\n')
f.write('\n')
f.write('@org_router.get("/my")\n')
f.write('def my_orgs(db: Session=Depends(get_db), current_user: User=Depends(get_current_user)):\n')
f.write('    memberships = db.query(OrgMember).filter(OrgMember.user_id==current_user.id, OrgMember.is_active==True).all()\n')
f.write('    result = []\n')
f.write('    for m in memberships:\n')
f.write('        org = db.query(Organisation).filter(Organisation.id==m.org_id).first()\n')
f.write('        if org:\n')
f.write('            count = db.query(OrgMember).filter(OrgMember.org_id==org.id, OrgMember.is_active==True).count()\n')
f.write('            result.append({"id":org.id,"name":org.name,"slug":org.slug,"role":m.role.value,"members":count})\n')
f.write('    return result\n')
f.write('\n')
f.write('@org_router.get("/{org_id}/members")\n')
f.write('def list_members(org_id: int, db: Session=Depends(get_db), current_user: User=Depends(get_current_user)):\n')
f.write('    members = db.query(OrgMember).filter(OrgMember.org_id==org_id, OrgMember.is_active==True).all()\n')
f.write('    result = []\n')
f.write('    for m in members:\n')
f.write('        u = db.query(User).filter(User.id==m.user_id).first()\n')
f.write('        if u: result.append({"user_id":u.id,"email":u.email,"full_name":u.full_name,"role":m.role.value})\n')
f.write('    return result\n')
f.write('\n')
f.write('@org_router.post("/{org_id}/invite")\n')
f.write('def invite_member(org_id: int, data: InviteCreate, db: Session=Depends(get_db), current_user: User=Depends(get_current_user)):\n')
f.write('    from datetime import datetime, timedelta\n')
f.write('    token = secrets.token_urlsafe(32)\n')
f.write('    invite = OrgInvite(org_id=org_id, email=data.email, role=OrgRole(data.role), token=token, expires_at=datetime.utcnow()+timedelta(days=7))\n')
f.write('    db.add(invite); db.commit()\n')
f.write('    return {"invite_token": token, "email": data.email, "role": data.role}\n')
f.write('\n')
f.write('@org_router.post("/accept-invite")\n')
f.write('def accept_invite(data: AcceptInvite, db: Session=Depends(get_db)):\n')
f.write('    from datetime import datetime\n')
f.write('    invite = db.query(OrgInvite).filter(OrgInvite.token==data.token, OrgInvite.is_used==False).first()\n')
f.write('    if not invite: raise HTTPException(status_code=400, detail="Invalid invite token")\n')
f.write('    user = db.query(User).filter(User.email==invite.email).first()\n')
f.write('    if not user:\n')
f.write('        user = User(email=invite.email, full_name=data.full_name, hashed_password=get_password_hash(data.password), role="ca_staff")\n')
f.write('        db.add(user); db.flush()\n')
f.write('    db.add(OrgMember(org_id=invite.org_id, user_id=user.id, role=invite.role))\n')
f.write('    invite.is_used = True; db.commit()\n')
f.write('    return {"message": "Joined successfully", "email": user.email}\n')
f.write('\n')
f.write('@org_router.delete("/{org_id}/members/{user_id}")\n')
f.write('def remove_member(org_id: int, user_id: int, db: Session=Depends(get_db), current_user: User=Depends(get_current_user)):\n')
f.write('    m = db.query(OrgMember).filter(OrgMember.org_id==org_id, OrgMember.user_id==user_id).first()\n')
f.write('    if m: m.is_active = False; db.commit()\n')
f.write('    return {"removed": True}\n')
f.close()
print('Org routes created')

# Alert Routes
f = open('app/api/routes/alert_routes.py', 'w')
f.write('from fastapi import APIRouter, Depends, BackgroundTasks\n')
f.write('from sqlalchemy.orm import Session\n')
f.write('from app.db.database import get_db\n')
f.write('from app.core.security import get_current_user\n')
f.write('from app.services.email.email_service import send_compliance_alerts, send_email\n')
f.write('\n')
f.write('alert_router = APIRouter(prefix="/alerts", tags=["Alerts"])\n')
f.write('\n')
f.write('@alert_router.post("/send-compliance")\n')
f.write('def trigger_alerts(background_tasks: BackgroundTasks, db: Session=Depends(get_db), current_user=Depends(get_current_user)):\n')
f.write('    background_tasks.add_task(send_compliance_alerts, db)\n')
f.write('    return {"message": "Compliance alerts queued"}\n')
f.write('\n')
f.write('@alert_router.post("/test-email")\n')
f.write('def test_email(current_user=Depends(get_current_user)):\n')
f.write('    ok = send_email(current_user.email, "AI Copilot Pro - Test Email", "<h2>Email working!</h2>")\n')
f.write('    return {"sent": ok, "to": current_user.email}\n')
f.close()
print('Alert routes created')

# Update main.py
content = open('main.py').read()
if 'gst_router' not in content:
    old1 = '    from app.api.routes.routes import ('
    new1 = '    from app.api.routes.gst_routes import gst_router\n    from app.api.routes.org_routes import org_router\n    from app.api.routes.alert_routes import alert_router\n    from app.api.routes.routes import ('
    old2 = '    app.include_router(chat_router, prefix="/api/v1")'
    new2 = '    app.include_router(chat_router, prefix="/api/v1")\n    app.include_router(gst_router, prefix="/api/v1")\n    app.include_router(org_router, prefix="/api/v1")\n    app.include_router(alert_router, prefix="/api/v1")'
    content = content.replace(old1, new1).replace(old2, new2)
    open('main.py', 'w').write(content)
    print('main.py updated')
else:
    print('main.py already updated')

# Create org tables
from app.db.database import engine, Base
from app.models.organisation import Organisation, OrgMember, OrgInvite
Base.metadata.create_all(bind=engine)
print('Org tables created')

print('\n✅ All done! Now run: uvicorn main:app --port 8000')