# -*- coding: utf-8 -*-
import io
from datetime import datetime

def generate_invoice_pdf(invoice_data, client_data):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm, leftMargin=2*cm, rightMargin=2*cm)
        styles = getSampleStyleSheet()
        elements = [
            Paragraph("TAX INVOICE", styles["Title"]),
            Spacer(1, 0.3*cm),
            Paragraph(f"Invoice #: {invoice_data.get('invoice_number','N/A')}", styles["Normal"]),
            Paragraph(f"Date: {invoice_data.get('invoice_date','')}", styles["Normal"]),
            Paragraph(f"Client: {client_data.get('company_name','')}", styles["Normal"]),
            Paragraph(f"GSTIN: {client_data.get('gstin','')}", styles["Normal"]),
            Spacer(1, 0.5*cm),
        ]
        data = [
            ["Description","Taxable Amt","CGST","SGST","IGST","Total"],
            ["Services/Goods",
             f"Rs.{invoice_data.get('taxable_amount',0):,.2f}",
             f"Rs.{invoice_data.get('cgst_amount',0):,.2f}",
             f"Rs.{invoice_data.get('sgst_amount',0):,.2f}",
             f"Rs.{invoice_data.get('igst_amount',0):,.2f}",
             f"Rs.{invoice_data.get('total_amount',0):,.2f}"],
        ]
        t = Table(data, colWidths=[5*cm,3*cm,2.5*cm,2.5*cm,2.5*cm,3*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTSIZE",(0,0),(-1,-1),9),
            ("GRID",(0,0),(-1,-1),0.5,colors.grey),
            ("ALIGN",(1,0),(-1,-1),"RIGHT"),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.5*cm))
        elements.append(Paragraph(f"Total: Rs.{invoice_data.get('total_amount',0):,.2f}", styles["Normal"]))
        elements.append(Paragraph("Generated by Maavi AI Copilot Pro", styles["Normal"]))
        doc.build(elements)
        buf.seek(0)
        return buf
    except Exception:
        buf = io.BytesIO()
        buf.write(f"Invoice {invoice_data.get('invoice_number','N/A')} - Rs.{invoice_data.get('total_amount',0):,.2f}".encode())
        buf.seek(0)
        return buf

def generate_report_pdf(report_data, client_name, period):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm, leftMargin=2*cm, rightMargin=2*cm)
        styles = getSampleStyleSheet()
        elements = [
            Paragraph(f"Financial Report - {client_name}", styles["Title"]),
            Paragraph(f"Period: {period} | Generated: {datetime.now().strftime('%d %b %Y')}", styles["Normal"]),
            Spacer(1, 0.5*cm),
        ]
        rows = [["Metric","Amount"]]
        for k,v in [("Total Revenue",report_data.get("total_revenue",0)),("Total Expenses",report_data.get("total_expenses",0)),("Net Profit",report_data.get("net_profit",0)),("Output GST",report_data.get("output_gst",0)),("Input GST",report_data.get("input_gst",0)),("Net GST Payable",report_data.get("net_gst",0))]:
            rows.append([k, f"Rs.{v:,.2f}"])
        t = Table(rows, colWidths=[8*cm,6*cm])
        t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1a1a2e")),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTSIZE",(0,0),(-1,-1),10),("GRID",(0,0),(-1,-1),0.5,colors.grey),("ALIGN",(1,0),(-1,-1),"RIGHT")]))
        elements.append(t)
        elements.append(Spacer(1, 0.5*cm))
        elements.append(Paragraph("Generated by Maavi AI Copilot Pro", styles["Normal"]))
        doc.build(elements)
        buf.seek(0)
        return buf
    except Exception:
        buf = io.BytesIO()
        buf.write(f"Report {client_name} {period}".encode())
        buf.seek(0)
        return buf
